### ISSUE TITLE
geninfo: WARNING: cannot find an entry for .gcov in .gcno file, skipping file

### ISSUE THREAD

**Issue by RickyZZQ** [linux-test-project/lcov#103]
gcc version: 10.1.0
lcov version: 1.14

The program can generate gcno and gcda. 
When lcov is executed，will be reported as follows:
"Processing test.gcda
geninfo: WARNING: /d/desktop/cov_test/test.gcno: Overlong record at end of file!
geninfo: WARNING: cannot find an entry for stdio.h##0bf0526485982f86885cac25381a7fde.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for stdio.h.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry test.c##d02a618fa88f46a768e6df00dddaad2a.gcov in .gcno file, skipping file!
geninfo:  WARNING: cannot find an entry test.c.gcov in .gcno file, skipping file!
Finished .info-file creation
Reading data file test.info
genhtml: ERROR: no valid records found in tracefile test.info"

How to fix this?

**Comment by henry2cox** [comment]
Dumb question:  what happens when you use an older gcc (say, gcc/9 or gcc/8)?
If older gcc works and newer does not – then we can check the generated data to see what is being produced that is not being handled.

Could be a geninfo bug, a gcov bug or a gcc bug…

Henry

**Comment by HDembinski** [comment]
I have the same problem, probably more people have this problem. How can it be that lcov works only with specific versions of gcc? In my experience, it worked only with gcc-5 and gcc-8.

**Comment by henry2cox** [comment]
FWIW;  we use lcov successfully with gcc 4,5,6,7,8,9, and 10.
We _do_ see slightly different coverage results for the same tests when run with different gcc toolchain versions.
(An interesting experiment is to generate coverage data with different compiler versions - then look at the differential coverage report when you compare any pair.  You might expect the results to be identical...but they are not.  Both hit/not hit and even "this line is code (or is not code)" show differences.

This isn't really a complaint...we can come up with actionable data, regardless of compiler version.

Henry

**Comment by xaizek** [comment]
> I have the same problem, probably more people have this problem.

I don't think the problem of this issue has been identified, you might have the same symptom though.

> How can it be that lcov works only with specific versions of gcc? In my experience, it worked only with gcc-5 and gcc-8.

Format of gcno/gcda isn't stable and can change between releases of GCC, this is why `lcov` might need to be adjusted for a particular GCC release. You might try enable use of intermediate format (also not terribly stable in last few releases, but it's supposed to stabilize eventually).

**Comment by footman199** [comment]
> I have the same problem, probably more people have this problem. How can it be that lcov works only with specific versions of gcc? In my experience, it worked only with gcc-5 and gcc-8.

Me too, and what is your specific version of gcc-8? My gcc-8.3 does not worked.

**Comment by MilicatZhang** [comment]
> Me too, and what is your specific version of gcc-8? My gcc-8.3 does not worked.
This issue probel could fix by update lcov version. When I use gcc-9.4 with lcov 1.14, could failed. Now I upgrade lcov version to 1.16.

**Comment by henry2cox** [comment]
Is this still an issue for anyone?
And if so, can you provide a small testcase that illustrates the problem?
Please include your gcc/llvm version and plaform (linux version ..., windows, macOS, or whatever).
Note that TOT contains some quite recent fixes for LLVM-11 - so please try the most recent lcov code, if you can.

Thanks.
Henry

**Comment by henry2cox** [comment]
Are you still seeing the issue with TOT?  Or just with the most recently released module?
The implementation has been extensively refactored - so the issue may (or may not) be fixed.
(We don't see it in any of our projects - but that might be because we don't do or don't have something in our project/code base that you do or have.)

Thanks
Henry

**Comment by henry2cox** [comment]
The originally reported issue looks very much like the one in #180 - which turns out to be an unsupported configuration.  (Trying to use "geninfo_intermediate = 0" in your lcovrc config file, with gcc/gcov version 9 or newer.)

I just added some additional error checks and warning messages to help diagnose/work around the issue.

Could you try current TOT, and see if you see any strange results and do NOT see any error messages?
That is:  the new checks cause geninfo to die with a (hopefully) helpful message.  geninfo should not produce any other strange messages, and should not produce incorrect or incomplete coverage data.

If commit sha 038c2ca22598bf645436806ecb5f16716a29b513 DOES fix the problem:  please close this issue.
If it does not...please help to provide a testcase so that we can debug it.

Hope this helps
Henry

**Comment by henry2cox** [comment]
Not sure about your specific version of centos - but I very strongly suspect that there is some YUM package that contains DateTime (no idea what package that might be).  
Internet suggests:  https://stackoverflow.com/questions/58307728/how-to-install-the-perl-datetime-module-under-centos8-yum-install-perldatetim

The perl way to do that is:
  perl -MCPAN -e "install DateTime"

**Comment by henry2cox** [comment]
Appears that issue is addressed/fixed quite some time back - so closing this issue.

If there is still a problem, please reopen this issue or file a new one.  Please include a detailed description of the problem and include a small testcase which illustrates the issue.
Thanks
Henry
