### ISSUE TITLE
Part of function call mark uncovered

### ISSUE THREAD

**Issue by lkersting** [linux-test-project/lcov#115]
I have a function call (m_vSchemaErrors.erase) that is split over multiple lines. It seems like the counter for the 1st line of the call is counted in the third line of the call (i.e. `98 :                                              m_vSchemaErrors.end());`). I am using 1.15 and gcc 9.2.0
~~~~
49 : void ErrExplicator::sortErrors()
      : {
49 :   std::sort(m_vSchemaErrors.begin(), m_vSchemaErrors.end());
   0 :   m_vSchemaErrors.erase(std::unique(m_vSchemaErrors.begin(),
49 :                                                                  m_vSchemaErrors.end()),
98 :                                              m_vSchemaErrors.end());
49 : }
~~~~

**Comment by henry2cox** [comment]
geninfo/lcov/genhtml are merely reporting the numbers generated by ‘gcov’.
geninfo/lcov/genhtml don’t actually know anything at all about your code.

Check your ‘.gcno’ and ‘.gcda’ data files…I suspect you will see the issue there.
You may (or may not) have success by updating tools.

Another approach is the hack/workaround that I took was to add some ‘filter’ features, to enable me to delete coverage data that was inconsistent or nonsensical.  The goal is a have usable/actionable result after filtering.

(My filters are easily defeated by a bloody-minded user;  mostly, I have succeeded to convince my users to not be bloody minded.  It is possible to make the filters more clever and less easily circumvented.)

(Yeah – my comment does not actually help you.)

Henry

**Comment by lkersting** [comment]
Thanks for the explanation. I guess my problem is with gcov. Have you seen a lot of issues like this for gcc 9.x? I can't find much that talks about it. Thanks!

**Comment by henry2cox** [comment]
Yes and no.

I found a lot of issues (strange or unusable or inconsistent results) with every version of gcov ☺
My workaround has been to filter out the offending data.
(My filters are not particularly clever – but could be made to be much more robust, if required.)

Henry

**Comment by xaizek** [comment]
@lkersting, coverage information is collected through counter increments inserted in the code by GCC. If compiler as a result of some optimizations failed to insert an increment (simple example: `if`-statement was replaced with a conditional assignment instruction), you won't see corresponding lines covered. So make sure to disable all optimizations.

Some open issues are described in [GCC's bug tracker](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=__open__&component=gcov-profile&product=gcc). If you report coverage bugs there, they might be fixed in future releases. However, these aren't serious bugs, so don't have too high hopes.
