### ISSUE TITLE
bazel test with copt="--coverage" leads to fail

### ISSUE THREAD

**Issue by TED-EE** [linux-test-project/lcov#117]
--copt="--coverage" can create .gcda files which is necessary. However, it led to fail when bazel test  //tests/...  --copt="--coverage".
The bazel test works if --copt="--coverage" is removed, but cannot create .gcda files.
So I wonder whether --copt="--coverage" adds some unexpected string unconsciously?

Thanks a lot!

**Comment by henry2cox** [comment]
Hard to know what your issue is without some information.

Does “failed” mean “failed to compile”, “failed to link”, “ran incorrectly” – or what?  How do you know it failed?  Did you get an error message?
What platform (linux, windows, mac…something else)?  What OS version?
What compiler/what version?
If someone was trying to diagnoe this…what else do you think they would need to know?

**Comment by Ted-EE** [comment]
Sorry for missing some essential infomation. 
The platform is Linux ubuntu.
The compiler is gcc 5.4.0.

When I entered bazel test --cache_test_results=no --local_test_jobs=1 --copt="--coverage" --linkopt="--coverage"  //thatFile The error message is "unexpect string not found in input" pointing to the first line of thatFile. But if I removed --copt="--coverage" from the command line, it succeeded. Moreover, if I entered bazel test --compilation_mode=dbg --cache_test_results=no --local_test_jobs=1 --copt="--coverage" --linkopt="--coverage"  //thatFile, it also succeeded.

I understood that the --copt passed the argument --coverage to the compiler, --coverage is a synonym for -fprofile-arcs -ftest-coverage (when compiling) and -lgcov (when linking) (https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#Instrumentation-Options). 
However, it seemed that --coverage led to something wrong that was so confused.

**Comment by henry2cox** [comment]
Unless I misunderstood your explanation – it seems like the issue is in ‘bazel test …’:  it is not configuring the build correctly/not passing compile and link options correctly.
We know this because you can go into the directories in question and set the flags and have everything build and link correctly.

I think that this means that your issue is not with gcov, lcov, or gcc.

Henry

**Comment by TED-EE** [comment]
Thanks for your kindly suggestion. I am following the cue and will give feedback soon.

**Comment by TED-EE** [comment]
Finally found the bug, a return was missed causing bazel test with --copt="--coverage" failed. 

The reason why the bazel test without --copt="--coverage" can succeed may come from that the compiler automatically inserts return 0 for the missed return. I supposed bazel test with --copt="--coverage" disabled the operation of the compiler automatically inserting return 0 for the missed return.

**Comment by henry2cox** [comment]
You might want to add “-Wall” (or similar) to your build flags – so the compiler can help you find such bugs.

Henry

**Comment by TED-EE** [comment]
Appreciate your suggestions.
