### ISSUE TITLE
sort result should use filename in case of equal score

### ISSUE THREAD

**Issue by bansan85** [linux-test-project/lcov#121]
I have a library with files without branch. genhtml sort these files always randomly between each other.

I can have :

![image](https://user-images.githubusercontent.com/9248729/114209558-0a60f000-995f-11eb-8b44-a818ad6c68e0.png)

![image](https://user-images.githubusercontent.com/9248729/114209572-0e8d0d80-995f-11eb-8c95-7dc07674138f.png)

![image](https://user-images.githubusercontent.com/9248729/114209577-10ef6780-995f-11eb-9a73-92e00c1c38cb.png)

I suggest to use filename as second criteria if score is the same.

**Comment by henry2cox** [comment]
FWIW:  the table sort in the version mentioned in pull request #86 supports the secondary sort you are looking for.
(If you don’t care about differential coverage, then you can use the enhanced tool for vanilla reports.)
You can try downloading that version and see if it solves your problem.

Henry

**Comment by bansan85** [comment]
Thanks, I try your version but without success. Can you tell me how to use the secondary sort ? Thanks
I used the same parameters that lcov:

./lcov/bin/genhtml --output-directory build/coverage --demangle-cpp --num-spaces 2 --sort --function-coverage --branch-coverage --legend build/coverage2.info

And I still have random output:

![image](https://user-images.githubusercontent.com/9248729/114604631-6eeeb880-9c99-11eb-8279-20bd47c1fa77.png)

![image](https://user-images.githubusercontent.com/9248729/114604643-731ad600-9c99-11eb-9593-34af6e7d0efd.png)

**Comment by henry2cox** [comment]
Hmm.

Should have worked.  I may have a bug.

Can you mail me the .info file so I can try it locally.

Thanks

Henry

**Comment by bansan85** [comment]
.info are generated with Github Actions and I don't have Linux at home.

But if I push the same commit twice, I have the same .info (except some lines are inverted): 


[coverage2.txt](https://github.com/linux-test-project/lcov/files/6306173/coverage2.txt)

[coverage2.txt](https://github.com/linux-test-project/lcov/files/6306174/coverage2.txt)

You can find complete report:

https://github.com/bansan85/jessica-ci/commit/24fbb9a6020a5d9a7da7d58b46b0967ec194b47e

https://github.com/bansan85/jessica-ci/commit/9e63d5db41ee6c65d804ad913bcf2ee8df0def43

And the workflow:

https://github.com/bansan85/jessica/blob/3ca664d0c8ba013920f668ee4e83ff77607fb616/.github/workflows/coverage.yml

**Comment by henry2cox** [comment]
No problem.

I’m pretty sure I found the bug – now trying to test whether my fix fixes the issue or not.

(But having troubles as it seems that someone in the IT department moved or deleted some perl modules I depend on ☹)

Hope to have a (tested) fix to you shortly….

Sorry about that.

Henry

**Comment by henry2cox** [comment]
I believe the issue is fixed now…can you try it again.

(Sorry for the delay – IT guys deleted a perl module I needed for testing…)

Henry

**Comment by bansan85** [comment]
Thanks, 12 hours to solve a problem is fast ;)

It's better. Files like "index-sort-b.html" is now fixed and predicatable.

But I still have random output for files like `.func.html` and `.func-sort-c.html`. You can have a look at https://github.com/bansan85/jessica-ci/commit/60bc0cd47b207ec1068551add5a4d35d895ddc6b

**Comment by henry2cox** [comment]
BTW: another way to sort is to use a 3-way key:

-          First by primary key (percentage, say)

-          Then by ‘missed’ lines if percentage is the same (IMO – more missed is more important)

-          Then by name if everything else matches.

I’ll look at the function list…see if I see an obvious error there too.
Are branches sorting correctly for you?

(BTW:  if you have tried to use branch coverage on C++ code and gave up due to all the bogus branches that are reported for exception return handlers – then you might want to take a look at the ‘—filter (branch,function,line)’ feature that I added.  Kind of a hack (OK - _really_ a hack) – but is does remove most of the useless noise.)

**Comment by henry2cox** [comment]
I think I fixed the ‘function’ issue too.  Still testing to be sure.

They should now sort using the name as the secondary key in both the vanilla and ‘alias’ tables…
(Yeah – famous last words.)

**Comment by henry2cox** [comment]
Pushed the fix –

Function coverage metrics should be using the function name as the secondary key now.  Sorry that it took 2 go arounds to resolve.

Please let me know, if you see other bugs or think of other features that might be useful.

Thanks

Henry

**Comment by bansan85** [comment]
Thanks for the new fix.

Unfortunately, it does not fix .h.func.html. See https://github.com/bansan85/jessica-ci/commit/6b0da760a618ad659f7f0615c2807a358ceb8733

I can have two different output :

![image](https://user-images.githubusercontent.com/9248729/114767310-c22f3c80-9d67-11eb-9ad5-ab7919d41755.png)

![image](https://user-images.githubusercontent.com/9248729/114767319-c52a2d00-9d67-11eb-8147-3b1f3ef708fb.png)

It could be great that sort by name use full length with arguments to avoid random sort.

**Comment by henry2cox** [comment]
Damn.
Sorry about that…but I think it is _finally_ fixed.

There is a kind of strange ‘no_sort’ flag which was having an effect.
Ah well.

**Comment by bansan85** [comment]
It's getting better and better :)

But I still have some pages with random output :/

You may have a look at https://github.com/bansan85/jessica-ci/commit/76ebda121c23cc081ea3f7726a50ba3ebd7f8987

![image](https://user-images.githubusercontent.com/9248729/114829643-a198ce00-9dcb-11eb-9177-2e5237d78e78.png)

![image](https://user-images.githubusercontent.com/9248729/114829654-a493be80-9dcb-11eb-9807-012c59acd862.png)

By the way, why there is two lines with different font / background color / alignment ?

**Comment by henry2cox** [comment]
Ah – sorry.  Missed exactly the same issue in a second location ☹.
Fixed now (I hope).

The different indentation and color is due to a change I had made in my version of lcov/genhtml to group ‘function aliases’ together.
The issue is that gcc will sometimes generate multiple variants of some functions (with slightly different names) – and then report that some of those aliases are hit and some not.  (You can find a discussion in issue #98.)
I decide that some function is an alias if gcov reports it to be on the same file and line.  (This _will_ cause certain generated default constructors, assignment operators, and destructors to all pretend to be aliases of each other…that could be fixed, but I didn’t care and so didn’t bother.)  It picks the alias with the shortest name as leader.

The white background is just the default color I had picked to have them stand out a bit (see the generated .css file).
In our projects – we always use differential reports (IMO, more informative/more actionable) – which then does slightly different colorization.

Taking a quick look at the code:  I don’t think I left you an easy way to turn off alias grouping.  (IMO:  I don’t think you really want to, especially if you are trying to act on the coverage reports.  Aliases just confuse things – especially as some of them are not reachable and will therefore appear uncovered in your report.)

Sorry that this has taken so many rounds to repair.

Henry

**Comment by bansan85** [comment]
No problem. I just noticed it and I wanted to report it. In my case, I don't think they are aliases but it's the same line due to macro usage.

I make another test and it work 🍾 I now have a fixed report 😄 

Hope your pull request will be integrated.

**Comment by bansan85** [comment]
@henry2cox Hi Henry,

I noticed another random output. This is still related to aliases I think.

![image](https://user-images.githubusercontent.com/9248729/117798714-b002ca00-b251-11eb-8e67-939ef1b4ba61.png)

![image](https://user-images.githubusercontent.com/9248729/117798752-b7c26e80-b251-11eb-943b-e56402fcfe07.png)

You may have an example of output here: https://github.com/bansan85/jessica-ci/commit/7fcfcee91695df164f76310174cacff35310ea6e

**Comment by henry2cox** [comment]
Ah…let me check.
I think I’m using the shortest name as the alias leader…but if there is more than one shortest name (equal length) – then I’m probably picking the one I found first…and I don’t remember what the function name visit order is.

Should be straightforward to take the lexically first name in that case (if that is indeed the bug).

Henry

**Comment by henry2cox** [comment]
I think I fixed it…

Henry
