### ISSUE TITLE
Closing Curly braces ("}") following return statements not ignored

### ISSUE THREAD

**Issue by bcaddy** [linux-test-project/lcov#129]
I found that `lcov` is reporting lines with just a `}` that follow a return statement when they should just be excluded. I don't see this issue in other peoples coverage reports and lcov does appear to be excluding the opening `{` properly. What am I doing wrong?

![last line issue](https://user-images.githubusercontent.com/41171425/129783734-9db7f741-e0fb-4826-81b5-0733e770910e.png)

**Comment by henry2cox** [comment]
You are doing nothing wrong (AFAIK).  The bogus lines seem to be coming from gcov.
You probably also noticed that those lines appear and disappear somewhat arbitrarily:  different compiler version, changed flags, new or changed code, etc.

I implemented a ‘--filter …” feature to remove (most of) these, plus a few other artifacts.
You can see some discussions in issues #101, #108, and #98, and a discussion of the fix in pull request #86.

You might want a more aggressive ‘line’ filter than the one I implemented.  My goal was to eliminate bogus “UIC” and “LBC” code from differential coverage reports (…because those categories trigger our Jenkins to fail the job).

Hope this helps

Henry

**Comment by bcaddy** [comment]
Thanks, is `--filter` merged into LCOV yet? It's not showing up as an option in my lcov install (v1.15) and I'm limited to officially released version on the systems I run on

**Comment by henry2cox** [comment]
Sorry – not merged.

There are two things you could do:

-          Download the fixed version and install somewhere in your sandbox.  (May not endear you to IT or security guys.)

-          Put some exclude directives around the braces where this is happening.
(This will be very painful/never-ending, as you will find new bogus lines appearing when you change code or environment – and even sometimes when you don’t.)

The last option is to wait for the pull request to be merged (but it has been a year – so I recommend not to hold your breath.)

Sorry to be the bearer of bad news.

Henry

**Comment by bcaddy** [comment]
Bummer, thanks for your help!

**Comment by bcaddy** [comment]
Thank you, I'll try it out.
