### ISSUE TITLE
geninfo: WARNING: could not open /Users/.../cover/Masonry/Masonry/MASUtilities.h

### ISSUE THREAD

**Issue by lilongcnc** [linux-test-project/lcov#133]
I put the. Gcno and. Gcda files in the cover folder and execute the command. 
` lcov --capture --directory cover --output-file coverage.info --no-recursion`

Errors encountered are as follows：
`
Processing RFPushView.gcda
geninfo: WARNING: could not open /Users/.../cover/Masonry/Masonry/MASUtilities.h
geninfo: WARNING: some exclusion markers may be ignored
Processing RFThemeConfigutation.gcda
Processing UIView+RFThemeColor.gcda
Processing RFThemeConfigutationS2.gcda
Processing UIImage+RFExtends.gcda
Finished .info-file creation
`

Then I run the genhtml command `genhtml -o html coverage.info --show-details` and the error is as follows：
`
Processing file /Users/lilong/.../cover/Masonry/Masonry/MASUtilities.h
genhtml: ERROR: cannot read /Users/..../cover/Masonry/Masonry/MASUtilities.h
`

I found that the RFPushView uses the masonry. If I remove the masonry from the RFPushView, lcov and genhtml will not report an error. But I definitely need Masonry. Can anyone help me?

**Comment by henry2cox** [comment]
If the text you are showing is _exactly_ what you see – you haven’t edited it in any way – then the paths reported by geninfo look odd.  “…” (3 periods in a row) is obviously a possible name for your directory – but it is a rather strange one.

The subsequent message from genhtml is telling you that it went looking for a file in that rather strange path – and was not able to find the file in question.
The message from geninfo looks similar:  it went to look at the source text (to see if there were any exclusion markers) and was not able to find the file either.

Where did your .gcda and .gcno files come from?  What path did you actually expect to see – e.g., for file “MASUtilities.h”?

If you can’t figure out why the input data files are corrupted, a hack would be to use ‘sed’ to munge the paths in the generated .info file so that genhtml will be able to find them.


Henry

**Comment by lilongcnc** [comment]
您好，你的邮件我已收到。我尽快处理的哈~~么么哒~~~

**Comment by GitMensch** [comment]
> See the "--substitute" option in lcov/geninfo/genhtml man pages. The regexps can also be put into your lcovrc file.

I so need that substitute option... but for it to be commonly available a new release is needed...


> Given the age of this issue, I will close it in a week or two if there are no further updates - or you can close it yourself. Conversely: if something is missing, please clarify so that it can be added or fixed.

Nothing missing but the close :-)

**Comment by henry2cox** [comment]
As threatened...closing this now.
Please reopen or file a new issue if there is still a problem.
Henry
