### ISSUE TITLE
lcov_excl_files option to exclude files from .lcovr config file

### ISSUE THREAD

**Issue by perror** [linux-test-project/lcov#149]
Right now, we can only exclude files through the `--exclude pattern` option. The configuration file has no keyword to specify it.

I would be convenient for many purposes to have something like this in the `.lcovrc` :
```
lcov_excl_files = *tests*
```
And exclude all the files that have `*tests*` in their path.

**Comment by henry2cox** [comment]
FWIW:  I added the “--include” and “--exclude” options to lcov and genhtml – such that they can be used at any point in our coverage flow.
Similarly, I added a “--filter region” option to enable the various stages to apply source exclusion markers or not.

These options are mostly hidden in makefiles and other scripts in our flow.  For the most part, “normal” users don’t invoke the tools, except through those wrappers.
(Too many options, too much code, too many paths that the specific individual may or may not care about.)

Henry

**Comment by perror** [comment]
In fact, I was really meaning keywords in the `.lcovrc` file because when `lcov` get executed by a third party software (such as `meson`), it is more convenient to specify all these in the configuration file than trying to tweak the third party software.

So, even a very simple patch to add the keywork such the following one, could make it easier :
```diff
diff --git a/bin/lcov b/bin/lcov
index 718f4c4..7eb4687 100755
--- a/bin/lcov
+++ b/bin/lcov
@@ -200,7 +200,7 @@ our $br_overall_found;
 our $br_overall_hit;
 our $func_coverage = 1;
 our $br_coverage = 0;
-
+our $exclude_files;
 
 #
 # Code entry point
@@ -257,6 +257,7 @@ if ($config || %opt_rc)
                "lcov_branch_coverage"  => \$br_coverage,
                "lcov_function_coverage"=> \$func_coverage,
                "lcov_fail_under_lines" => \$opt_fail_under_lines,
+               "lcov_excl_files"       => \$exclude_files,
        });
 }
 
@@ -903,7 +904,7 @@ sub lcov_geninfo(@)
        foreach (@include_patterns) {
                @param = (@param, "--include", $_);
        }
-       foreach (@exclude_patterns) {
+       foreach (@exclude_patterns, $exclude_files) {
                @param = (@param, "--exclude", $_);
        }
 
diff --git a/man/lcovrc.5 b/man/lcovrc.5
index 330362f..736627d 100644
--- a/man/lcovrc.5
+++ b/man/lcovrc.5
@@ -999,6 +999,15 @@ Specify the regular expression of lines to exclude from exception branch coverag
 Default is 'LCOV_EXCL_EXCEPTION_BR_LINE'.
 .PP
 
+.BR lcov_excl_files " ="
+.I expression
+.IP
+Specify the regular expression of file paths to exclude.
+.br
+
+Default is 'LCOV_EXCL_FILES'.
+.PP
+
 .BR lcov_fail_under_lines " ="
 .I percentage
 .IP
```

**Comment by eli-schwartz** [comment]
Bit difficult to inspect a thirty thousand line diff, my browser doesn't even want to render the page in the first place.

Looking at the more leisurely one and a half thousand line lcovrc man page in git master:
https://github.com/linux-test-project/lcov/blob/238ea7c33ca0b96654ee9f4b5c770792954a40f3/man/lcovrc.5#L1437-L1465

This seems to be what is wanted here. For my part, this addition means that I could remove this code: https://github.com/mesonbuild/meson/blob/d490636328e78984af0b80c70a8217c4f9cf9c52/mesonbuild/scripts/coverage.py#L134-L139

It runs as a post-processor:

```python
            # Remove all directories inside subproject dir
            subprocess.check_call([lcov_exe,
                                   '--remove', covinfo,
                                   os.path.join(subproject_root, '*'),
                                   '--rc', 'lcov_branch_coverage=1',
                                   '--output-file', covinfo] + lcov_config)
```

**Comment by perror** [comment]
Well, I did not find what I wanted in the links. But, I might certainly have missed it. My point was to discard some directory patterns (e.g. "*tests*") from the coverage computation. This is already covered through the command line option `--exclude` but my concern is to use a `lcovrc` file with this information. Not sure that there is an option to specify exclusion pattern from the configuration file (or, at least, I did not find it in the diffs I saw).

**Comment by henry2cox** [comment]
If I understood:  I think this is in the current TOT 'lcovrc' file (between lines 251-259:
(Cannot upload image..not sure why).

On issue for you might be that this option uses a glob match (not a regexp).  OTOH:  the "lcov --remove" pattern is also a regexp.
You can specify more than one pattern (all are applied).

Another change that might help in your flow is that you can pass multiple "--config-file ..." options to your genhtml/lcov/geninfo command.  That way, you can have a project-wide set of standard options which each team can add to or override/change. 

> genhtml  --config-file project.rc --config-file team.rc ....

The team that didn't care about some set of directories could just add corresponding patterns in their "team.rc" file.

I'm not entirely sure if that meets your requirement or not, though.
Henry

**Comment by perror** [comment]
Yes, I found it thanks to your indications and I think you are right ! This should exactly match my need, I will try it asap.
```
exclude = */tests/*
```
Thanks a lot!

**Comment by henry2cox** [comment]
Great I guess we can close this one (presuming that your test works, of course).
Henry

**Comment by perror** [comment]
I'll reopen if it doesn't work but my guess is that this will be fine.

**Comment by henry2cox** [comment]
Hope so...but please reopen (or open new request) if you find some other useful feature that is not present or does not work.

**Comment by henry2cox** [comment]
One thing I forgot to mention:

If you put the exclude option in your RC file, then you might not want to use that file for all of the lcov tools.

The issue:

-  is that lcov, geninfo, and genhtml will all read that RC file - and will all attempt to apply the exclusion.

-  However:  when the exclusion is applied during "lcov --capture ..." - then the matching data will be removed from the generated .info file.

- Now when you run genhtml,  or "lcov --add" with that .info file as input, the 'exclude' pattern will not see any matches.
That will cause an error message of the form "'exclude' pattern ... is unused ...". 

You can suppress or ignore the message, of course - but you may prefer add the pattern(s) to the particular tool command line rather than to the RC file ... or to use a tool-specific RC file.  The best/most convenient approach will depend on how your verification environment and project team are organized.

(The messages exist due to environment bugs that we found in some projects.  The basic assumption is that the user would not have bothered to specify something if they didn't think that it would apply.  Thus - if the tool wasn't able to use the pattern, then it is likely that there is some other configuration issue such that the extracted project data is incomplete/missed something that we thought would be there.  We want our jenkins jobs to run completely unattended/without supervision or manual review - so it is important that possible misconfiguration is caught quickly...before we cause a DV screwup.
Your environment and priorities might be different.)
