### ISSUE TITLE
geninfo: Can't call method "files" on an undefined value at /home/runner/.local/bin/../lib/lcovutil.pm line 3162

### ISSUE THREAD

**Issue by eyal0** [linux-test-project/lcov#174]
https://github.com/linux-test-project/lcov/blob/master/lib/lcovutil.pm#L3156-L3161

This function appears to require more than one argument.

5fd02c8098593986594bdfaf5cda9a96e2a2cc2a is the first bad commit

**Comment by eyal0** [comment]
https://github.com/pcb2gcode/pcb2gcode/actions/runs/3560745376/jobs/5981015084 shows the breakage

**Comment by henry2cox** [comment]
Thanks for the report.  
Turns out that an internal project had found that bug too.
The actual issue is that we can see undef child data if there was an error processing the gcda file (e.g., the file contains no valid data).
I was planning to push a fix for that plus a few other issues, later today or tomorrow.
Thanks for finding the bug - and sorry that you found it before I fixed it.
Henry

**Comment by henry2cox** [comment]
Got to this faster than I expected to.
Should be fixed in sha 4d044cb...

Please reopen and/or file new report if this issue is still present or if you see any other issues or strange results.

Henry
