### ISSUE TITLE
genhtml: ERROR: cannot create directory 

### ISSUE THREAD

**Issue by marischan888** [linux-test-project/lcov#175]
Can someone help solve the genhtml issue? When I am trying to generate the Html from the info file, it shows:
mkdir: cannot create directory ‘area\\include’: No such file or directory
genhtml: ERROR: cannot create directory 'area\include'!

**Comment by henry2cox** [comment]
Could you provide a bit more information:
  - what lcov version are you using?
  - what platform (linux, windows, mac, ...)?
  - what was your genhtml command line?

From the very terse explanation:  it looks like you may be running genhtml from some directory that you do not own/do not have write permission to - and you have not used the "-o output_directory_name" argument to tell genhtml to write somewhere else.  As a result, genhtml is trying to write the coverage report to "."; one of your source files is in a directory called "...area/include" (say, file name "...area/include/foo.c" - with some filesystem prefix identified and elided) - and genhtml is trying to create a corresponding directory for you in the report.  That mkdir command fails due to permissions.

**Comment by marischan888** [comment]
> 
Thank you for your reply. My lcov version is 1.15.alpha0w and the platform is Windows. I did tell genhtml to write to a newly-created directory names coverage. Is my situation related to permissions? If it is, how can I fix it?
`genhtml --branch-coverage -o datastore_ut datastore_llt.info`

**Comment by henry2cox** [comment]
Yes - it looks like this is related to permissions.
Was 'datastore_ut' a pre-existing directory/part of your project?
Or is it just a name that you want to write to?
What do you see inside that directory? what happens when you type "mkdir datastore_ut ; mkdir datastore_ut/area ; mkdir datastore_ut/area/include'?
My suspicion is that you need to direct the output to a location that you have write permission.  I don't know the layout of your machine or your sandbox, so I cannot tell you where that might be.

**Comment by marischan888** [comment]
> Yes - it looks like this is related to permissions. Was 'datastore_ut' a pre-existing directory/part of your project? Or is it just a name that you want to write to? What do you see inside that directory? what happens when you type "mkdir datastore_ut ; mkdir datastore_ut/area ; mkdir datastore_ut/area/include'? My suspicion is that you need to direct the output to a location that you have write permission. I don't know the layout of your machine or your sandbox, so I cannot tell you where that might be.

**Comment by marischan888** [comment]
> Yes - it looks like this is related to permissions. Was 'datastore_ut' a pre-existing directory/part of your project? Or is it just a name that you want to write to? What do you see inside that directory? what happens when you type "mkdir datastore_ut ; mkdir datastore_ut/area ; mkdir datastore_ut/area/include'? My suspicion is that you need to direct the output to a location that you have write permission. I don't know the layout of your machine or your sandbox, so I cannot tell you where that might be.

datastore_ut is the result folder. I try to mkdir a result directory datastore_ut manually but the same error still pops up. I think it is not related to the permission.
`mkdir datastore_ut`
`genhtml -o datastore_ut datastore_llt.info --branch-coverage`

**Comment by henry2cox** [comment]
so you are trying to write to a new output directory, a directory which did not exist before and which the tool will create.
When you try manually, you are able to use mkdir to create that directory, and you are able to use mkdir to create subdirectories into the location you created manually.  Thus, we conclude that you _do_ have the required permissions.
When you run your genhtml command (writing to a new location - so we know it is writing all clean data):
  - do you see any output from the tool at all (console log messages, anything at all?
  - after it dies:  has it created your output directory?
  - if yes:  is there anything in the output directory?  (Any files, subdirectories - anything at all?? ("ls -R ...")
Next question is what your data file looks like.
What do you see from "grep SF: datastore_llt.info"  (I'm looking for a list of the source file names that genhtml knows about).
The more relevant and useful information you can provide, the more likely remote internet debugging will be successful.
My other suggestion is to download the most recent lcov version (from master) and try that one.  I know that code much better than the older version - and it contains a fair bit of infrastructure for debugging configuration issues.  (However:  it is not well tested on windows.  YMMV.)

**Comment by marischan888** [comment]
> 

There are only some png files in the result folder. yes, the output folder is successfully created. 
grep SF: datastore_llt.info returns a list of source files, including all header files and cpp files.
Sorry for the limited information since the company privacy.

**Comment by henry2cox** [comment]
Some additional diagnostic messages have been added.
Could you try your example again (using the lcov version from TOT) .
If anything goes wrong - please update this issue report - otherwise, please close.
Thanks
Henry

**Comment by henry2cox** [comment]
Checking if there are still problems here - or if this issue can be closed.

**Comment by henry2cox** [comment]
No update in 6 months.  Closing issue as completed.

If there is still a problem:  please either reopen this issue or file a new one.  Please provide a detailed description of the problem - and ideally, a testcase which illustrates the issue.
Thanks
Henry
