### ISSUE TITLE
False positive branches are reported when passing expression into macro

### ISSUE THREAD

**Issue by ttanxuyen** [linux-test-project/lcov#184]
Hi,

I have an issue where LCOV reports false positive branches if passing expression into macro. Could you please help to take a look and fix it?

Thanks and Regards,
Xuyen

Here is the issue in details.

•	No branches counted when passing a Boolean to macro
![image](https://user-images.githubusercontent.com/55272258/211488391-a7f267af-2197-46af-9a4d-a28ecaaf9600.png)
•	No branches counted when create a expression in macro
![image](https://user-images.githubusercontent.com/55272258/211488454-09b5f996-78de-49e1-8153-7a18ea01fe8b.png)
•	Branches are counted when passing an expression to macro
![image](https://user-images.githubusercontent.com/55272258/211488506-9aebfd15-38a5-4b40-b6b9-c6a7ec92e342.png)

Here is code example.

#include<iostream>
using namespace std;

#define VERIFY(expr) if (!(expr)) { cout <<"Verification failed " << endl; return -1; }

#define VERIFY2(_a, _b) if (!(_a > _b)) { cout <<"Verification failed " << endl; return -1; }

int Sub(int a, int b){
  VERIFY(a>b);

  VERIFY2(a, b);

  bool check = (a>b);
  VERIFY(check);

  return (a - b);
}

**Comment by henry2cox** [comment]
I rather strongly suspect that you didn't explain your experiment completely.
Specifically, I think that you ran your testcase, then collected coverage data via:
  $ lcov -c -d . -o test.info --filter branch  <- note branch filter enabled.

If we leave off the filter - then we see the expected branches for all 3 instantiations of the macro.
This is not a bug - it is correct behaviour.  If you don't want to see branches there, then you can use exclusions to remove them.

If we turn on branch filtering:  the filter regexp does not see anything it recognizes as a conditional on the 2nd and 3rd instances - and so removes the associated branches.
This might not be desirable - but is expected behaviour.  To do better, we would need to be an actual compiler - not a perl regexp.

I know that your example is artificial, and is merely trying to represent the situation in your actual code (complicated!) in a tiny example (simple!) - however, coverage tools in general are not really happy with macros.
It is a much, much better idea to use inline functions, lambdas, and templates to achieve the same effect.  That is almost always possible (but yes - our code base also contains macros in some places :-( )
In this case, you could even change your code to contain 2 inlines with different signatures - and you should see the branch in both of them.  
You could even use the new "erase-functions" feature to remove the coverpoints from one of them, leaving the other :-).

Sorry for the long explanation.
I may not have understood what you are trying to do, or what behaviour you think is incorrect.

Henry

**Comment by henry2cox** [comment]
A bit of clarification - lest someone else see or have the same issue.
Here is a testcase:
`#include <iostream>
using namespace std;

#define VERIFY(expr) if (!(expr)) { cout <<"Verification failed " << endl; return -1; }

#define VERIFY2(_a, _b) if (!(_a > _b)) { cout <<"Verification failed " << endl; return -1; }

int Sub(int a, int b){
VERIFY(a>b);

VERIFY2(a, b);

bool check = (a>b);
VERIFY(check);

return (a - b);
}

int main(int ac, char ** av)
{
   Sub(1,2);
   return 0;
}
`
Compiled and run using gcc/10.2.0:

> "
$ g++ --coverage test.cpp
$ ./a.out
Verification failed 
$ lcov --capture -o test.info --branch-coverage -d .
Capturing coverage data from .
geninfo cmd: '/mtktools/Utility/como/tools/mtk/diffcov/2.0.17/bin/geninfo . --output-filename test.info --parallel 1 --memory 0 --branch-coverage'
Found gcov version: 10.2.0
Using intermediate gcov format
Writing temporary data to /tmp/geninfo_datC1RF
Scanning . for .gcda files ...
Found 1 data files in .
Processing test.gcda
Finished .info-file creation
$ genhtml -o noFilter --branch-coverage test.info
Found 1 entries.
Found common filename prefix "/home/hcox/coverage"
Writing .css and .png files.
Generating output.
Processing file lcov/test.cpp
  lines=9 hit=5
Overall coverage rate:
  lines......: 55.6% (5 of 9 lines)
  functions......: 100.0% (2 of 2 functions)
  branches......: 16.7% (1 of 6 branches)
$ genhtml -o withFilter --branch-coverage --filter branch test.info
Found 1 entries.
Found common filename prefix "/home/hcox/coverage"
Writing .css and .png files.
Generating output.
Processing file lcov/test.cpp
  lines=9 hit=5
Overall coverage rate:
  lines......: 55.6% (5 of 9 lines)
  functions......: 100.0% (2 of 2 functions)
  branches......: 50.0% (1 of 2 branches)
Filter suppressions 'branch':
    2 instances
    4 coverpoints

> 

For unknown reasons, github won't let me upload screenshots of the generated report ("Something went really wrong, and we can't process that file.  Try again").

However, you can see the summary at the end of genhtml generation:  "no filter" found 6 branches of which one was hit, and "with filter" found 2 branches of which one was hit.
The branch that wasn't filtered out is on line 9 of the example.

(If someone else is really interested - perhaps they could use the above testcase and commands to generate the HTML reports, and then append to this issue.  Might help someone else in the future.  Or might not.)

In any case:  I think that your testcase (or my version of it) is doing exactly what we expected - but may or may not be what you wanted.
Please clarify the desired behaviour and/or close this issue.

Hope this helped

Henry

**Comment by ttanxuyen** [comment]
Thanks for your explanation in details. It's very useful for me. I'm going to close the issue now.
