### ISSUE TITLE
Help with the conda-forge package

### ISSUE THREAD

**Issue by MuellerSeb** [linux-test-project/lcov#219]
Version 2 of LCOV has some problems in the conda-forge package because of some dependencies:
https://github.com/conda-forge/lcov-feedstock/pull/10

Maybe someone here has an idea how to approach this.

Cheers, Sebastian

**Comment by henry2cox** [comment]
I was hoping someone else would respond - but not so far.
Could you clarify the question?
From the linked report, it appears that your platform is missing some required perl packages.  Thus:  you need to install those required modules.
I guess your platform _does_ have a perl installed - else lcov 2.0.16 would not have worked either - so this should be a 'simple' matter of just figuring out how those other modules were specified and installed - and then repeating that.
Note that you will also need a python and an xlsxwriter package in order to successfully run the lcov regression suite.
Python is a new requirement for lcov 2.0 - and your platform may not be configured to handle it.

Hope that helps.
Henry

**Comment by henry2cox** [comment]
I think that - if you are happy with lcov 1.16, then you can continue to use it.
If you want to upgrade to take advantage of new features:  then you will have to upgrade.

The errors you were seeing earlier WRT function end-line derivation are due to inconsistent data generated by your version of gcc/gcov.  You can add the suggested 'ignore' flags or turn off end-line derivation if you like (see the man pages).
Which version are  you using?  This has been tested and is known to work with gcc/4.8.5, 5.2.0, 6.2.0, 8.3.0, 10.2.0 and (I think) 12.2.0 - all on some flavor of linux/unix.  llvm/11.0.0 and 15.0.7 are also known to work (but are not currently supported through the lcov test framework).  Other versions and other platforms may or may not also work.

Contributions which expand the set of supported compilers, compiler versions, and platforms are highly appreciated.
Contributions which merely test existing code and say "yeah - this also worked on P using C/V" are also useful.  Maybe we need a 'community' page which lists all the platforms, versions, etc. which have been tested and/or which are known to be broken.

> So my questions:

> are some of these perl modules part of the perl conda-forge package by default?

I fear that I do not know what conda or conda-forge are - so cannot help you there.

> are really all these modules needed to use LCOV?

Yes and no.
Yes:  they are used to (portably) implement some set of features.
No:  there is always another way to do it.
But this works today - and so nobody is likely to rewrite.

> you mentioned python as a dependency. Are there some python packages needed?

"needed" for testing - specifically, to generate spreadsheets for CPU performance monitoring.
Required - if you want to modify lcov.  Not required if you just want to run the tool.

There is a list of required packages in the README.

My guess is that this doesn't really help you.  Sorry.
Henry

**Comment by MuellerSeb** [comment]
> I fear that I do not know what conda or conda-forge are - so cannot help you there.

OK, that explains some things. I am not doing anything own my own system here. The linked repository is the "official" package recipe for LCOV in the conda-forge ecosystem. Conda is an open source package management system and environment management system.

I am just a supporting volunteering maintainer there to help keeping it up-to-date, but I am a bit puzzled with the latest update and the CI failing for it.

**Comment by henry2cox** [comment]
section 3 - Dependencies - of the README.
Either in the top level directory of the repo you cloned displayed in the top level lcov project page in github.  (Scroll down a bit).

**Comment by MuellerSeb** [comment]
I already saw that section. I was just wondering if really all of these are "new" dependencies, that were not required by v1.16:

  - Capture::Tiny
  - DateTime
  - Devel::Cover
  - Digest::MD5
  - File::Spec
  - at least one flavor of JSON module.
    In order of performance/preference:
       - JSON::XS
       - Cpanel::JSON::XS
       - JSON::PP
       - JSON
 - Memory::Process
 - Time::HiRes

**Comment by henry2cox** [comment]
Digest::MD5 was also a dependency in v 1.16.
DateTime might have been as well (cannot remember).
The others are "new".

I confess to be not entirely sure why it matters, as you need all of them.
