### ISSUE TITLE
Mistake in count of line coverage

### ISSUE THREAD

**Issue by MMelzig** [linux-test-project/lcov#22]
following situation has been extracted form real code:

#include <stdlib.h>                              /* for exit() */

unsigned int UuT(void)
{
	unsigned int true_var  = 1;
	unsigned int false_var = 0;

	unsigned int ReturnStatus_t = 0;
	if (false_var) {
		ReturnStatus_t = 1;
	}	
	else	{
		if (true_var) {
			if (true_var) {
				ReturnStatus_t = 0;
			}
			else {
				if (true_var) {
					ReturnStatus_t = 0;
				}
				else {
					**/* Following line falsely marked as covered when parameter "--rc lcov_branch_coverage=1" is set */**
					ReturnStatus_t = 0;
				}
			}
		}
		else {
			ReturnStatus_t = 0;
		}
	}
	return (ReturnStatus_t);
}

int main(int argc, char** argv) {
	UuT();
    return 0;
}

This c-code compiled with an old as well as the current cygwin package (gcov versions 4.8.2 and 6.3.0) causes a faulty count of the line - marked with a comment - during line coverage.

lcov and genhtml has been executed with to following script:

#!/bin/bash
[ "$COMSPEC" ] && set -o igncr; # Ignore CR if on Windows system

./Debug/LCOV_Test.exe

lcov -c -d Debug -o LCOV_Test_wb.info --rc lcov_branch_coverage=1 --checksum
genhtml LCOV_Test_wb.info -o ./lcov_wb

lcov -c -d Debug -o LCOV_Test_wob.info --rc lcov_branch_coverage=0 --checksum
genhtml LCOV_Test_wob.info -o ./lcov_wob

The version with the setting --rc lcov_branch_coverage=0 doesn't count the marked line as executed correctly.
The version with the setting --rc lcov_branch_coverage=1 count the marked line as executed falsely.

Used lcov version was 1.13.

For me it looks like a bug and I hope the effect is reproducible.

Best regards
MMelzig

**Comment by oberpar** [comment]
Thanks for reporting this issue. I was able to reproduce it with the current LCOV git version and gcc 4.8.5. It appears that gcc's gcov produces incorrect coverage data when run with the -a option on your source file:

    $ gcov -a test.c
    File 'test.c'
    Lines executed:76.47% of 17
    Creating 'test.c.gcov'

In test.c.gcov, line 23 shows an incorrect line execution count of 1:

    [...]
            -:   21:                                else {
            -:   22:                                        /* Following line falsely marked as covered when parameter "--rc lcov_branch_coverage=1" is set */
            1:   23:                                        ReturnStatus_t = 0;
        $$$$$:   23-block  0
            1:   23-block  1
            -:   24:                                }
            -:   25:                        }
            -:   26:                }

As LCOV relies on the data produced by gcov, this bug cannot be fixed in LCOV. Please report it to the GCC team (see https://gcc.gnu.org/bugs/).

You can specify `--rc geninfo_gcov_all_blocks=0` to the lcov tool as a workaround. This will tell LCOV not to use gcov's -a option, though this comes at the cost of some branch coverage granularity.

**Comment by MMelzig** [comment]
Thanks for the feedback. The workaround works, and the lost of granularity can be accepted. A bug report is added for GCC team: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79891
