### ISSUE TITLE
Lcov2.0 filters normal branched when --filter branch and no_exception_branch=1 both works

### ISSUE THREAD

**Issue by Allen19930926** [linux-test-project/lcov#279]
Hi Henry,
Sorry to bother you! However I have another trouble in branch filtering. Due to the restriction to some 3rd party libraries, my project could not use compilation parameter - "-fno-exceptions". I filter the bogus branch by lcov. Use no_exception_branch=1 when lcov 1.15, and --filter branch when lcov 2.0-1.  
Now with cross compilation and remote gcda data collection, the "--filter branch" does not make a satisfying result, while I know this is most possily caused by gcov version mismatch which is a hot potato. According to this, I use both "no_exception_branch=1" and "--filter branch", and get a strange branch filtering results which filteded many normal branches.  Please pay some time to analyze this issue.
Thanks a lot. I'm looking forward to your reply soon.

**only --filter branch**
![image](https://github.com/linux-test-project/lcov/assets/60568441/c10d88bb-5231-4abe-bb8a-85e91adf9414)

**--filter branch and no_exception_branch=1 both works**
![image](https://github.com/linux-test-project/lcov/assets/60568441/9bed8a78-0874-4e23-88cc-76d9ca223798)

**Comment by henry2cox** [comment]
Your first snapshot looks like you applied exception filtering;  it tends to leave single orphan branches in place.
If that isn't what you did/is not what you expected: then this looks like a bug - or at least a case I don't recall having seen.

Your second snapshot looks wrong.  It appears as if the actual branches on your if/else expressions were removed - which is definitely not what is supposed to happen.

Three things to do next:
  - verify the parameters you are passing to `lcov --capture` and `genhtml`.
  Exception filtering should be removing exception branches (possibly leaving orphans).  Branch filtering should be removing branches that aren't associated with conditional expressions. 
  If this is not what is happening:  please send a testcase which illustrates the issue, so I can see what is happening.

  - Download/clone the current top-of-tree and see if the most recent code illustrates the same issues.
  If so...then I probably need a testcase.

  - Update to newer compiler version (...which is likely not possible for your project, and may not help resolve case in any event).

Branch filtering will remove exception branches on lines where the tool doesn't think it found a conditional expression...but you may need exception filtering as well if those exception branches are associated with lines which _do_ contain conidtional expressions.  (Without data from gcov/llvm-cov, the tool can't distinguish the exception handlers from the conditionals.)

As with your other case:  you can turn up verbosity and/or debug logging so the tool will tell you a bit more about what it is filtering/why it is filtering something - but that probably won't be useful to you.  Debugging aid more than user feature.

**Comment by henry2cox** [comment]
Your example is incomplete.
No definition for your LcovTest class.  No definition for your TEST_F macro.  No makefile or compile/link command line.
Example needs to be complete, correct, and runnable in order to be useful.

**Comment by Allen19930926** [comment]
Hi Henry，I have uploaded my demo project, please download to analyse this issue.  It was compiled by cmake and sh build.sh would complie and execute the demo.  build.sh contains lcov command, and I'm sure the project will reproduce the issue.

[gtest_demo.tar.gz](https://github.com/linux-test-project/lcov/files/14805934/gtest_demo.tar.gz)

**Comment by henry2cox** [comment]
Ran your example - and cannot reproduce the issue you describe.

There are (at least?) 2 bugs/issues in your example:
  - the `lcov --capture` command you are using did not turn on `--branch-coverage`. 
  Branch coverage is not enabled, by default - so I guess that is why you didn't see branches in your output.
  I don't know why you _did_ see branches in your earlier example - but my suspicion is that you simply dropped a flag and didn't notice.
  - your cmake environment seems to use llvm - or at least, uses llvm when I build locally (possibly because it is in my path?)
  But - despite using LLVM to generate your coverage data (*.gcno, *.gcda), you are using the default `gcov` to extract the data.
  You wanted to use `llvm-cov gcov ...`.
  This probably worked for you because you have gcc/4.9 in your path - so we picked up gcov from the gcc package.  Te llvm-generated gcov data is (mostly) in gcc/4 format - so it didn't die.  Despite that it appeared to work, it is recommended to use the same toolchain to extract the data as you used to build it.  Discussion page #234 talks about llvm.

In addition, your coverage report is rather noisy and shows lower coverage than you probably wanted because it includes a bunch of gtest and stl code that you probably don't care about.  You might want to use `--include 'app/*'` on your capture or genhtml command line - to report only your application code.  You might also want a `--flat` or `--hierarchical` report - as the default format is a bit of overkill for a 2-file project.

There may still be a bug here - but this example does not appear to demonstrate it.

**Comment by Allen19930926** [comment]
Henry, please set branch_coverage=1 in lcovrc or add --rc branch_coverage=1, the issue may be reproduced.


**there are the more detailed descriptions**

- please treat this issue as a new and independent one, and could be reproduced on a PC with ubuntu 18.04. The gcc version is gcc version 7.5.0
- sorry for my vague descriptions about lcov configuration.  Actually, as you know, the lcov configuration is consist of two parts, lcovrc and lcov command --rc.   I turn the branch coverage on in lcovrc and keep other configurations the same as lcov repository, meanwhile remain the differential options in lcov command, such as the --rc no_exception_branch=0/1, in order to change it quickly.  At the base of this, I conduct the coverage report with branch coverage. If the parameter branch_coverage was 0,  the report would not show branches row in summary table header like this. 
![image](https://github.com/linux-test-project/lcov/assets/60568441/17775892-c1b5-4181-a1b2-92e840215405)

- Maybe, there is nothing about LLVM In my CMakeLists.txt. I haven't tried llvm-cov so far...
- As for the report noise, I use -e "*test_code*" to only extract the code I care about. If there is any optimal point in my lcov command, please tell me straightly, after all you are the expert in lcov.


happy weekend~

**Comment by Allen19930926** [comment]
Henry, please set branch_coverage=1 in lcovrc or add --rc branch_coverage=1, the issue may be reproduced.


**there are the more detailed descriptions**

- please treat this issue as a new and independent one, and could be reproduced on a PC with ubuntu 18.04. The gcc version is gcc version 7.5.0
- sorry for my vague descriptions about lcov configuration.  Actually, as you know, the lcov configuration is consist of two parts, lcovrc and lcov command --rc.   I turn the branch coverage on in lcovrc and keep other configurations the same as lcov repository, meanwhile remain the differential options in lcov command, such as the --rc no_exception_branch=0/1, in order to change it quickly.  At the base of this, I conduct the coverage report with branch coverage. If the parameter branch_coverage was 0,  the report would not show branches row in summary table header like this. 
![image](https://github.com/linux-test-project/lcov/assets/60568441/17775892-c1b5-4181-a1b2-92e840215405)

- Maybe, there is nothing about LLVM In my CMakeLists.txt. I haven't tried llvm-cov so far...
- As for the report noise, I use -e "*test_code*" to only extract the code I care about. If there is any optimal point in my lcov command, please tell me straightly, after all you are the expert in lcov.


happy weekend~

**Comment by henry2cox** [comment]
I fear that you need to submit a different test case or a simpler driver.
When I run this one locally, it doesn't show branches because branch coverage is not enabled.
When I enable branch coverage, I see branches where we expect them, and none where we don't - so everything looks fine.

It is certainly possible that things look different in your environment.  Your goal is to capture that difference in as simple a test as possible - so the issue can be reproduced.
I'm afraid that hacking your cmake environment, gtest, or whatever - to see if I can make something fail - is not something I'm particularly interested in doing.

**Comment by Allen19930926** [comment]
I understand you that to analyse the difference between enviroments is quite a disappointing thing. So I add -v to collect lcov running log, could you find something wrong in the logs? 

**As is shown below, the branch data differentiated after extracting . Branch data decreased to 0 at extracting step executed by lcov.** 

Some enviroment version info is at the end of picture such as cmake, lcov, gcc and etc.  As now I am back home , the version in my home laptop is a little different than my office laptop, but the issue also occured.
﻿
**branch exist**
![branch](https://github.com/linux-test-project/lcov/assets/60568441/c13161ee-b2a4-47a2-ab94-76ecb2b75cd0)

**branch disappear**
![no_branch](https://github.com/linux-test-project/lcov/assets/60568441/87fa01bf-720d-4eb8-8e2d-13be541fabbc)

**Comment by henry2cox** [comment]
I don't really need the log.
Far easier is if you simply attach the `app.info` file that is generated by the `lcov --capture` command in your testcase script.

**Comment by Allen19930926** [comment]
Good news. Here is the app.info generated by my script. Hope to be helpful.
[appinfo.tar.gz](https://github.com/linux-test-project/lcov/files/14823195/appinfo.tar.gz)

**Comment by Allen19930926** [comment]
make latest lcov, bugfixed. commit-id:70a44f841bd99826d6f9e6df89897d2a6b9b2fe0

thanks!
