### ISSUE TITLE
I see functions as uncovered although they are covered

### ISSUE THREAD

**Issue by ziad-fernride** [linux-test-project/lcov#319]
I am using lcov version 2.1, and I see this in the coverage report:

<img width="830" alt="Screenshot 2024-09-06 at 16 51 00" src="https://github.com/user-attachments/assets/0943cdde-4c73-4c58-aa48-4d96488f5e13">

As you can see, every single line in the function is marked covered, but somehow the function signature line is not. 

I this command to generate the report:
```
exec tools/coverage/genhtml_wrapper \
    "${coverage_report}" \
    --output-directory "$coverage_report_out_dir" \
    --prefix "$source_dir" \
    --source-directory "$source_dir" \
    --ignore-errors unmapped,category \
    --legend \
    --branch-coverage \
    --filter function \
    --quiet \
    --synthesize-missing \
    --title="${RELEASE_VERSION:-unknown}"
```

**Comment by henry2cox** [comment]
Do you have a testcase which exhibits the issue?
Which platform, compiler, and compiler version?
If LLVM:  are you using the gcov- or profdata- path?

Does lcov/genhtml know about the function?  (Does that name appear in the coverage DB?)

**Comment by ziad-fernride** [comment]
I use llvm ... I take the gcov path.

The file is known by the report:
```
FN:368,377,_ZN5project7namespace10RingBufferINS_7network12BytesPayloadILm320EEENS0_16BoundedHeapArrayIS4_EEE14increment_sizeEv
FN:368,377,_ZN5project7namespace10RingBufferImNSt3__16vectorImNS2_9allocatorImEEEEE14increment_sizeEv
```

```
DA:368, 0
DA:370,9691
DA:372,9691
DA:374,3615
DA:375,3615
```

**Comment by ziad-fernride** [comment]
is it possible for a function to have 0 coverage when all lines are covered ? Do functions need all branches to be covered as well for them to be covered ?

**Comment by henry2cox** [comment]
> is it possible for a function to have 0 coverage when all lines are covered ? Do functions need all branches to be covered as well for them to be covered ?

If data is valid/consistent:  no.  Function cannot have non-zero hit count unless at least one line (...the first one) also has a non-zero hit count, and vice versa.

Somebody could easily be generating invalid data :-(

In this case, the incorrect data is very likely coming from llvm/llvm-cov - but is possibly due to a bug in lcov.
Things like optimization and inlining can make accurate tracking difficult for the compiler and the runtime.
Would need to investigate the testcase and the LLVM data more carefully, to diagnose.

It might be a useful to try LLVM/16 or newer - if you are not already using.
Also worth trying the profdata path to see how different it is (very likely, very different - and again, a differential report compaing the gcov to profdata paths and/or to compare gcc to llvm - is a good way to figure it out).  Alan Phips is very good at addressing issues, when you find them.

**Comment by ziad-fernride** [comment]
Thanks for the hints :-) 
One other thing that could be relevant, is that the class where this function lives is a template class.

**Comment by ziad-fernride** [comment]
so it could be a filtering problem maybe, where one type did not hit this function while the others did ? Will look a bit into that and see if I can see something plausible there

**Comment by henry2cox** [comment]
> so it could be a filtering problem maybe, where one type did not hit this function while the others did ? Will look a bit into that and see if I can see something plausible there

If you apply `--filter function`, then function aliases are grouped such that the group count is aggregated - though you can still see the hit count of the individual aliases.
That may or may not help with the situation you observe.

**Comment by henry2cox** [comment]
consistency checks are in SHA 4543c3688.

I think it is worth trying your testcase again with an updated version - and see what it tells you.
Of course:  if your data is inconsistent, there may not be much that you can do about it - unless you happen to be a tool developer and can fix the issues.
However:  at least in our applications, we depend a lot on the data - so really, really want to know if our trust is misplaced.

**Comment by henry2cox** [comment]
As mentioned above:  I think that the above SHA addresses the problem here - appears to be inconsistent coverage data generated by LLVM (and/or Coverage.py).
In particular, in the opening example, the tool should now report that the function coverage info is inconsistent with its line coverage content.  If the message is ignored (downgraded to a warning):  then the hit count of the function will be adjusted such that the function is 'hit'.  Similarly, the converse case.

If there are no updates, then I will close this issue in a couple of days.

**Comment by henry2cox** [comment]
As threatened...no updates, so i am closing this one now.
If there is still a problem, please either reopen this issue or file a new one.
Please include a testcase which exhibits the bug.
Thanks
