### ISSUE TITLE
Solution to the inconsistency between the compilation environment and the test environment

### ISSUE THREAD

**Issue by W-M-R** [linux-test-project/lcov#351]
When the compilation environment and the test environment are different, is there any simpler way besides copying the source code to the test environment to make the file path consistent?

**Comment by W-M-R** [comment]
Can I modify the path in the generated coverage.info file to achieve my goal?Is there any better way, or does lcov provide an option to modify this path?

**Comment by henry2cox** [comment]
> Can I modify the path in the generated coverage.info file to achieve my goal?Is there any better way, or does lcov provide an option to modify this path?

Yes.  the .info file is just text - `sed` is your friend (and does nothing more and nothing less than the `--substiture` option).  The `--resolve-script` callback can be far more sophisticated - which can be necessary in a complex build environment, when you find the number of substitutions to be getting out of hand and/or when some of the substitutions are optional.

**Comment by hartwork** [comment]
Regarding `sed`, I think I'm currently doing something very close at https://github.com/libexpat/libexpat/blob/493406dbcc915c8209514241297fd2734a9e3a9b/expat/coverage.sh#L212 . (I'm not saying it's the best way.)

**Comment by henry2cox** [comment]
If you like standard external tools:  `sed` is fine - and what you are doing is entirely obvious to the next guy along (though maybe not as clear why you need to do it).
If you like self-contained command lines:  then the `--substitute` approach might be better.  (There is a valid argument that this makes both what and why nonobvious...especially if your command line extends across 3 or 4 lines.)

(We use `--substitute` for simple things and callbacks when things get complicated - at least in part, because callbacks can be separately tested and can generate actionable errors if something unexpected happens.)

**Comment by W-M-R** [comment]
Thank you @henry2cox, @hartwork  very much, I know what to do next

**Comment by henry2cox** [comment]
I guess that the other thing which is obvious is that - depending on the features you are using - the file paths in your baseline coverage DB, current coverage DB, diff file, source directory, annotations, and versions all have to match - or all have to handle whatever differences exist (_e.g._, between revision control and build layout).

**Comment by W-M-R** [comment]
Yes, any discrepancy may result in the final generated report being incorrect
