### ISSUE TITLE
lcov trace file includes coverage data only for header files but not source file

### ISSUE THREAD

**Issue by arjunurs** [linux-test-project/lcov#76]
I'm using lcov to generate coverage reports for our test suite, but the tracefile seems to have coverage data only for header files. The error messages indicate that the source files cannot be found. The code is compiled by a Jenkins job on a build machine and the tests are executed as a downstream job on another slave. The source code and gcno files are transfered to the downstream job, which then executes the call to lcov. Here are the details.

Path to gcno and gcda files on slave that executes test: 

/home/jenkins/workspace/Test1/dir1/dir2/dir3/App/build/Debug/src/CMakeFiles/dir4/unity_build/*.{gcda,gcno,o}

Path to source file:

/home/jenkins/workspace/Test1/dir1/dir2/dir3/App/src/

Working directory:

 /home/jenkins/workspace/Test1/dir1/dir2/dir3/App/

lcovrc:

geninfo_adjust_src_path = /home/jenkins/workspace/App-Build-Job/App/src => /home/jenkins/workspace/Test1/dir1/dir2/dir3/App/src

Lcov command:

lcov --capture --config-file lcovrc --base-directory src --directory . --output-file xp-intermediate-tracefile.info"

Error messages:

Processing CMakeFiles/dir4/unity_build/example.cpp.gcda
Cannot open source file /home/jenkins/workspace/App-Build-Job/App/src/example.cpp
geninfo: WARNING: skipping empty file example.cpp##f2f2aa6a0b7869b554d4c2f549123eaf.gcov

I'm not sure what I'm missing.

Thanks

**Comment by oberpar** [comment]
The `Cannot open source file...` warning is emitted by the `gcov` tool and should not have any actual effect. The `geninfo_adjust_src_path` directive only affects the coverage data files generated by `lcov`. The main question is why the gcov file turns up empty.

My suggestion would be to re-run the lcov call with the --debug switch, look for the `gcov` invocation (starts with `DEBUG: system(gcov`), and then run that command line manually. This should narrow down the issue to `gcov` behavior that might be better explained.

**Comment by arjunurs** [comment]
Thanks. I looked for the `gcov` invocation using the `--debug` option. This is what I found for one of the source files

gcov /home/jenkins/workspace/Test1/dir1/dir2/dir3/App/build/Debug/src/CMakeFiles/dir4/unity_build/Manager.cpp.gcda -o /home/jenkins/workspace/Test1/dir1/dir2/dir3/App/build/Debug/src/CMakeFiles/dir4/unity_build -b -x

Output:
Cannot open source file /home/jenkins/workspace/App-Build-Job/App/src/dir5/dir6/Manager.cpp
.
.
.
File '/home/jenkins/workspace/App-Build-Job/App/src/dir5/dir6/Manager.cpp'
Lines executed:0.00% of 247
Branches executed:0.00% of 2362
Taken at least once:0.00% of 2362
Calls executed:0.00% of 1642
Creating 'Manager.cpp##b3b6887a027db5dc65615933b4b12fce.gcov'

Contents of gcov file:
$ cat Manager.cpp##b3b6887a027db5dc65615933b4b12fce.gcov
        -:    0:Source:/home/jenkins/workspace/App-Build-Job/App/src/dir5/dir6/Manager.cpp
        -:    0:Graph:/home/jenkins/workspace/Test1/dir1/dir2/dir3/App/build/Debug/src/CMakeFiles/dir4/unity_build/Manager.cpp.gcno
        -:    0:Data:/home/jenkins/workspace/Test1/dir1/dir2/dir3/App/build/Debug/src/CMakeFiles/dir4/unity_build/Manager.cpp.gcda
        -:    0:Runs:34
        -:    0:Programs:1

**Comment by arjunurs** [comment]
@oberpar Any thoughts what might be the issue? I've tried `--base-directory` and `--config-file` with `geninfo_adjust_src_path` setting.

**Comment by oberpar** [comment]
This appears to be a `gcov` problem - normally `gcov` creates output including coverage data even if the source file cannot be accessed. What version of GCC are you using?

Since `lcov` cannot modify the paths that `gcov` is using to access the source code, the only workaround would be to present the source code files at exactly the location that gcov expects (e.g. by using a symbolic link).

**Comment by arjunurs** [comment]
@oberpar Thanks for your response. We are using gcc 8.3.1 20190311. I will try to investigate why gcov doesn't output coverage data.

The workaround does fix this issue but my concern is that it will be unreliable if there is a build job running on the Jenkins slave. I will have to skip creating a symbolic link if the directory has already been created by another build job.

**Comment by henry2cox** [comment]
FWIW:  there is a different fix (or workaround) available in the current TOT.
The "--substitute" command line option (and equivalent lcovrc option) applies user-specified regexp substitutions to the paths found in the gcov files (as well as in other input data).
This feature was implemented for exactly your use model:  source code layout (e.g., in revision control) does not match build structure (e.g., due to shared components).
This issue has been open for 2.5 years - and may no longer be of interest to you.
Please take a look at TOT and see if that resolves the problem - and then close or update this report.
(I'm trying to clean up resolved things to make it easier to find unresolved stuff.)
Thanks
Henry

**Comment by henry2cox** [comment]
Going ahead to close this issue, as I think it is resolved and/or has not been updated in years.

If the problem persists, please reopen this issue or file a new one.  Please give a detailed description of the problem and ideally, provide a testcase which exhibits the issue.
