### ISSUE TITLE
Function coverage with abstract class

### ISSUE THREAD

**Issue by wakenhole** [linux-test-project/lcov#79]
Hi, 

There is an issue for the abstract class.
Based on gcc, compiler create a hidden base destructor, and it is included as the target function of lcov. 
Accordingly, the function coverage is less than 100%, even if line coverage is 100%. 
Do you have any idea for this?

-------------------------------------------
Command
-------------------------------------------
```
g++ -std=c++11 -fprofile-arcs -ftest-coverage --coverage test.cpp -o test
./test 
lcov -c -d . -o coverage.info
genhtml --legend --demangle-cpp coverage.info -o html
```

-------------------------------------------
Code
-------------------------------------------
```
#include<iostream>
class Animal
{
public:
    Animal()
    {   
        std::cout << "Animal" <<std::endl;
    } 
    virtual ~Animal()
    {   
      std::cout << "~Animal" <<std::endl;
    }   
};

class Cat : public Animal
{
public:
    Cat()
    {   
        std::cout << "Cat" <<std::endl;
    }   
    ~Cat()
    {   
        std::cout << "~Cat" <<std::endl;
    }   
};

int main()
{
    Animal* animal = new Cat;
    delete animal;
    Cat* cat = new Cat;
    delete cat;
    Cat cat2;
}
```
------------------------------------------
Result
------------------------------------------
> Animal
> Cat
> ~Cat
> ~Animal
> Animal
> Cat
> ~Cat
> ~Animal
> Animal
> Cat
> ~Cat
> ~Animal
> Capturing coverage data from .
> Found gcov version: 7.5.0
> Using intermediate gcov format
> Scanning . for .gcda files ...
> Found 1 data files in .
> Processing test.gcda
> Finished .info-file creation
> Reading data file coverage.info
> Found 2 entries.
> Found common filename prefix "/home/ohlee/Study"
> Writing .css and .png files.
> Generating output.
> Processing file test/test.cpp
> Processing file /usr/include/c++/7/iostream
> Writing directory view page.
> Overall coverage rate:
>   lines......: 100.0% (24 of 24 lines)
>   functions..: 88.9% (8 of 9 functions)

**Comment by henry2cox** [comment]
The issue here is a feature of gcc/gcov such that gcc has generated 2 variants of two of your methods.
Those variants have different mangled named (but demangle to the same string) - and one of them is not called.
I suspect that you could work around the problem by moving the method implementations out of the class decl, or by adding a no_inline pragma to them.

For example, in the gcc/4.8.3 output, we see that the functions are called:
>FN:15,_ZN6AnimalC2Ev
FN:19,_ZN6AnimalD0Ev  <- this one is "Animal::~Animal()"
FN:19,_ZN6AnimalD2Ev  <- and so is this
FN:28,_ZN3CatC2Ev
FN:32,_ZN3CatD2Ev 
FN:32,_ZN3CatD0Ev
FN:38,main
FNDA:3,_ZN3CatD2Ev
FNDA:2,_ZN3CatD0Ev
FNDA:1,main
FNDA:0,_ZN6AnimalD0Ev
FNDA:3,_ZN6AnimalD2Ev
FNDA:3,_ZN3CatC2Ev
FNDA:3,_ZN6AnimalC2Ev

There is no way for lcov to know that these really are identical - instead, it thinks that they may be two differently parameterized template instances.

However, after adding demangling support to geninfo, I get the desired behaviour:
> FN:15,Animal::Animal()
FN:19,Animal::~Animal()
FN:28,Cat::Cat()
FN:32,Cat::~Cat()
FN:38,main
FNDA:5,Cat::~Cat()
FNDA:1,main
FNDA:3,Animal::~Animal()
FNDA:3,Cat::Cat()
FNDA:3,Animal::Animal()

If the variants had been different, then the demangled names would be different (reflecting parameterization) - and would have been held as variants/aliases (see the TOT doc regarding "--filter function").

I will push the enhancement after some additional testing is complete.

Henry

**Comment by henry2cox** [comment]
The enhancement described above is in SHA 218beb05d4a5.
In view of the age of this issue and that I think that it is fixed, I will close this issue now.
If you feel that something is missing, please reopen.

Henry

**Comment by xaizek** [comment]
> I suspect that you could work around the problem by moving the method implementations out of the class decl, or by adding a no_inline pragma to them.

This shouldn't make any difference. It was bothering me a bit, so I found it in GCC:

https://github.com/gcc-mirror/gcc/blob/95dc11475dac06b5eecd904079de8aa94827a36a/gcc/cp/mangle.cc#L2044-L2046

What I see in the disassembly is that D0 calls D1 and then `::operator delete(void *)` on `this`. D1 is a weak reference to D2. D2 restores vtable pointer in `this`, destructs fields, destructs parent object. While removing `virtual` from the destructor removes D0 from the picture and moves `::operator delete(void *)` call to `main()`.

So demangling or otherwise collapsing all D* functions into a single entry is the right thing to do.
