### ISSUE TITLE
Inline styles interfere with Content-Security-Policy

### ISSUE THREAD

**Issue by Pesa** [linux-test-project/lcov#87]
`genhtml` uses inline styles in a couple of places. These are incompatible with Content Security Policy (CSP) and are generally frowned upon. For example, Chrome reports the following error on a generated HTML file served with a restrictive CSP:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-NV51liJZAXsbth1BfTtTnceCkaOTzEBaJxsjPABraDI='), or a nonce ('nonce-...') is required to enable inline execution.

See https://developers.google.com/web/fundamentals/security/csp#inline_code_is_considered_harmful for more information and https://content-security-policy.com/unsafe-inline/ on why adding `unsafe-inline` to the CSP is not really an option.

Given that `genhtml` already relies on an external CSS, I wonder if the inline styles could be moved to that file too?

**Comment by henry2cox** [comment]
> genhtml uses inline styles in a couple of place

Could you clarify what those places are/what the suspect code is?
Please use the version from current TOT (top of tree).  It has been significantly enhanced since august 2020 - so the issues you ran into might have been fixed inadvertently.

I will assume that the issue is fixed or not reproducible if there are no updates in a couple of weeks.
Thanks.
Henry

**Comment by henry2cox** [comment]
No responses/no updates - so I assume that this issue has been addressed.

If there is still a problem, please either reopen this issue or file a new one.
Please include a detailed description of the problem, and ideally include a testcase which exhibits the issue.
Henry
