### ISSUE TITLE
MASTER VERSION DOES NOT WORK WELL UNDER MINGW GCC 5.1

### ISSUE THREAD

**Issue by xiaoyun94** [linux-test-project/lcov#88]
MASTER VERSION DOES NOT WORK WELL UNDER MINGW GCC 5.1
use genhtml it show:
geninfo: WARNING: could not open xxx,
after printing param $filename in function get_source_data manually, i found there is a charater \r as the end, so that it cannot be read correectlly.

**Comment by xiaoyun94** [comment]
1.14 works well

**Comment by xiaoyun94** [comment]
write_source func has same problem

**Comment by oberpar** [comment]
This seems like a bug in MINGW:
```
$ gcov --version
gcov (MinGW.org GCC Build-2) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

$ gcov -i example.gcda -t
{
	"gcc_version": "9.2.0",
[...]
	"current_working_directory": "C:\nUsers\nuser\nAppData\nLocal\nTemp\nlcov\nexample",
	"data_file": "example.gcda"
}

```
The value for the the `current_working_directory` key in the JSON output contains newlines `'\n'` where escaped backslashes `'\\'` are expected. Note that this causes problems in LCOV master branch now because here support for parsing the JSON intermediate format was added for the first time.

As a workaround you can try to specify the base-directory on the command line so that LCOV ignores the incorrect value provided by `gcc`.
```
lcov -c -d . --base-directory . -o test.info
```

**Comment by oberpar** [comment]
I added 25ff79cebc249918342a6eb550ea13d20472232f that implements a workaround in LCOV.

**Comment by xiaoyun94** [comment]
THX

**Comment by mkauli** [comment]
same for me: MINGW64_NT-10.0 / gcc V7.1.0 / gcov V7.1.0

1.5 & master does not work
1.4  works well

**Comment by xiaoyun94** [comment]
> same for me: MINGW64_NT-10.0 / gcc V7.1.0 / gcov V7.1.0
> 
> 1.15 & master does not work
> 1.14 works well

i have a pr to solve this problem
