### ISSUE TITLE
Switch from JSON to JSON::PP slows down geninfo considerably

### ISSUE THREAD

**Issue by nehaljwani** [linux-test-project/lcov#94]
It is my mistake. I should have benchmarked it before submitting a pull request at https://github.com/linux-test-project/lcov/pull/89

Turns out `JSON` is a thin wrapper over `JSON::XS`, which uses a compiled extension whereas `JSON::PP` is just pure perl.

On 416 files (the speed difference is ginormous) :
```
JSON::PP -> real    21m6.189s
JSON::XS -> real    0m43.148s
```

Not a perl expert, but should we do something like https://github.com/p5sagit/JSON-MaybeXS/blob/a677b4fa8bfb1017b70d536cea9b6269fced6dbf/lib/JSON/MaybeXS.pm#L10-L30 ?

**Comment by henry2cox** [comment]
The code in pull request #86 addresses this issue (but that request is mainly about differential coverage support - I needed to fix the JSON issue because it was so slow that our Jenkins jobs would not complete).

**Comment by henry2cox** [comment]
An alternative might be to use my version; it addresses the slowdown issue and also implements a number of other features as well, the most useful of which is ‘differential coverage’.  Pull request #86 contains some of the description – and from there, you can find the papers, etc.

We use this version on a couple of code bases with ~400K LOC and a few thousand files (most of which are testcase sources which are ultimately filtered out and not displayed in the final reports).
Performance is not what I’d like – but will likely require rewrite into C++ to see dramatic improvement.

Henry

**Comment by xaizek** [comment]
@AlexandreBossard You can try disabling use of intermediate format, then there will be no JSON parsing.

> Performance is not what I’d like – but will likely require rewrite into C++ to see dramatic improvement.

@henry2cox As mentioned in #78, `lcov` runs `gcov -i` for every input file separately instead of passing many files at the same time. I think your version does the same. Passing files at once seems to reduce time it takes gcov to process coverage by a factor of 5.4 on 571 files in a simple test I ran. However, mind that `--preserve-paths` and `--hash-filenames` is ignored for `--json-format`, which needs to be worked around (the fix will probably be available in GCC 11.3, it was [backported](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89961#c28) to GCC 11 branch).

**Comment by henry2cox** [comment]
Ø  Passing files at once seems to reduce time ….

@xiazek Thanks – I did not know that. Or if I knew, I had forgotten.

Do you have a changelist that implements that optimization?   Otherwise, I will try to reproduce it and see if the limitations bite in the projects that I care about, or not – and if I can work around them if they do.

Unfortunately, I think it will be some time before I can move some of the projects to gcc/11 ☹

Henry

**Comment by xaizek** [comment]
> Do you have a changelist that implements that optimization?

I don't know Perl and tested by changing code of my own tool, but it can even be done on command-line (should have thought of this earlier...). Running times are greater in this case, but the speedup I observe is basically the same:

```bash
# one file at a time
time find -name '*.gcda' -exec gcov --json-format {} \; > /dev/null
# as many files at a time as possible
time find -name '*.gcda' -exec gcov --json-format {} \+ > /dev/null
```

> Unfortunately, I think it will be some time before I can move some of the projects to gcc/11

That's not a problem, you just need to avoid passing files with identical names at the same time. This might result in 2-3 invocations of `gcov` instead of 1, which isn't a big deal.

**Comment by henry2cox** [comment]
Thanks…
Quick clarification:  I just need to avoid passing files with the same basename (but different directory) – right?

**Comment by xaizek** [comment]
> I just need to avoid passing files with the same basename (but different directory) – right?

Yes, because name of an output file depends only on basename and `gcov` ends up overwriting files it creates if names match. Implementation is [here](https://github.com/xaizek/uncov/blob/7594ba688f7b6b8d21e0cfa0a73e8539e2a9a3fa/src/GcovImporter.cpp#L254), but the workaround is probably the only interesting detail about it.

Another interesting thing that came up in that bug ticket is a new option called `--stdout`, which makes things even faster (400ms -> 250ms in this case; no disk IO, file search or compression/decompression). I haven't tried parsing its output yet, but it's just one JSON dictionary per line.
